/**
 * Tema portado do protótipo em HTML (code.html), que carregava o Tailwind via CDN
 * e configurava tudo em uma tag <script id="tailwind-config">.
 *
 * Tudo fica em `extend` para preservar os defaults do Tailwind, exatamente como
 * no protótipo (é por isso que `rounded-2xl`, usado na seção de curiosidades,
 * continua valendo 1rem mesmo sem estar declarado aqui).
 */
/** @type {import('tailwindcss').Config} */
export default {
  darkMode: "class",
  content: ["./index.html", "./src/**/*.{js,jsx}"],
  theme: {
    extend: {
      colors: {
        error: "#ffb4ab",
        "on-background": "#e5e1e6",
        "secondary-fixed": "#ffe088",
        "on-surface": "#e5e1e6",
        "primary-fixed-dim": "#e1c46e",
        "tertiary-container": "#ffd384",
        "on-secondary-container": "#342800",
        primary: "#fff5e1",
        surface: "#131316",
        "on-primary": "#3c2f00",
        outline: "#98907f",
        "surface-bright": "#39393c",
        "on-tertiary": "#412d00",
        "surface-container": "#1f1f22",
        "surface-container-highest": "#353438",
        "surface-container-low": "#1b1b1e",
        "primary-container": "#f5d77f",
        "surface-container-lowest": "#0e0e11",
        "on-primary-fixed-variant": "#574500",
        "surface-variant": "#353438",
        "on-surface-variant": "#cfc6b3",
        "tertiary-fixed-dim": "#f4be53",
        "secondary-container": "#af8d11",
        "inverse-on-surface": "#303033",
        "inverse-primary": "#725c0f",
        "error-container": "#93000a",
        background: "#131316",
        "primary-fixed": "#ffe087",
        "on-tertiary-fixed": "#271900",
        secondary: "#e9c349",
        "on-secondary": "#3c2f00",
        "secondary-fixed-dim": "#e9c349",
        "on-tertiary-container": "#7c5800",
        "surface-container-high": "#2a2a2d",
        "on-tertiary-fixed-variant": "#5e4200",
        "tertiary-fixed": "#ffdea6",
        "inverse-surface": "#e5e1e6",
        "on-error": "#690005",
        "surface-dim": "#131316",
        "on-error-container": "#ffdad6",
        "on-secondary-fixed-variant": "#574500",
        "on-primary-container": "#725c0f",
        "surface-tint": "#e1c46e",
        "outline-variant": "#4c4638",
      },
      borderRadius: {
        DEFAULT: "0.125rem",
        lg: "0.25rem",
        xl: "0.5rem",
        full: "0.75rem",
      },
      spacing: {
        "space-2xl": "4rem",
        margin: "4rem",
        "gutter-mobile": "1rem",
        gutter: "1.5rem",
        "space-xl": "2.5rem",
        "space-xs": "0.25rem",
        "space-md": "1rem",
        "space-lg": "1.5rem",
        "margin-mobile": "1.25rem",
        "space-sm": "0.5rem",
      },
      fontFamily: {
        "headline-sm": ["Bodoni Moda"],
        "label-sm": ["Plus Jakarta Sans"],
        "headline-xl-mobile": ["Bodoni Moda"],
        "body-md": ["Plus Jakarta Sans"],
        "label-lg": ["Plus Jakarta Sans"],
        "headline-lg": ["Bodoni Moda"],
        "headline-md": ["Bodoni Moda"],
        "headline-xl": ["Bodoni Moda"],
        "display-hero-mobile": ["Bodoni Moda"],
        "body-sm": ["Plus Jakarta Sans"],
        "display-hero": ["Bodoni Moda"],
        "body-xl": ["Plus Jakarta Sans"],
      },
      fontSize: {
        "headline-sm": ["1.25rem", { lineHeight: "1.75rem", fontWeight: "400" }],
        "label-sm": [
          "0.6875rem",
          { lineHeight: "1rem", letterSpacing: "0.14em", fontWeight: "700" },
        ],
        "headline-xl-mobile": ["2rem", { lineHeight: "2.5rem", fontWeight: "500" }],
        "body-md": ["1rem", { lineHeight: "1.5rem", fontWeight: "400" }],
        "label-lg": [
          "0.875rem",
          { lineHeight: "1.25rem", letterSpacing: "0.08em", fontWeight: "600" },
        ],
        "headline-lg": ["2rem", { lineHeight: "2.5rem", fontWeight: "500" }],
        "headline-md": ["1.5rem", { lineHeight: "2rem", fontWeight: "400" }],
        "headline-xl": [
          "3rem",
          { lineHeight: "3.5rem", letterSpacing: "-0.01em", fontWeight: "500" },
        ],
        "display-hero-mobile": [
          "2.75rem",
          { lineHeight: "3rem", letterSpacing: "-0.01em", fontWeight: "600" },
        ],
        "body-sm": ["0.875rem", { lineHeight: "1.25rem", fontWeight: "400" }],
        "display-hero": [
          "4.5rem",
          { lineHeight: "4.75rem", letterSpacing: "-0.02em", fontWeight: "600" },
        ],
        "body-xl": ["1.125rem", { lineHeight: "1.75rem", fontWeight: "300" }],
      },
    },
  },
  plugins: [],
};
